<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenCode.Sdk\OpenCode.Sdk.csproj" />
    <ProjectReference Include="..\..\src\OpenCode.Core\OpenCode.Core.csproj" />
    <ProjectReference Include="..\..\src\OpenCode.Schema\OpenCode.Schema.csproj" />
    <ProjectReference Include="..\..\src\OpenCode.Server\OpenCode.Server.csproj" />
    <ProjectReference Include="..\..\src\OpenTui.Native\OpenTui.Native.csproj" />
    <ProjectReference Include="..\..\src\OpenCode.Client\OpenCode.Client.csproj" />
    <ProjectReference Include="..\..\src\OpenTui.Blazor\OpenTui.Blazor.csproj" />
  </ItemGroup>

</Project>